// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrogw7sv4VvRUfEWAdfPbn7u6-Lz1jHTo',
    appId: '1:758008299790:web:f0c198248a3e4ae81fd75f',
    messagingSenderId: '758008299790',
    projectId: 'fir-project-26e52',
    authDomain: 'fir-project-26e52.firebaseapp.com',
    databaseURL: 'https://fir-project-26e52-default-rtdb.firebaseio.com',
    storageBucket: 'fir-project-26e52.appspot.com',
    measurementId: 'G-9C85CXLBN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5b4vglrQ81XWE7U_vXJrqCDZ0KTDLXyg',
    appId: '1:758008299790:android:1d9b4a3b11f7815a1fd75f',
    messagingSenderId: '758008299790',
    projectId: 'fir-project-26e52',
    databaseURL: 'https://fir-project-26e52-default-rtdb.firebaseio.com',
    storageBucket: 'fir-project-26e52.appspot.com',
  );
}
